version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    env_file:
      - app.env
    ports:
      - '6000:27017'
    networks:
      - app
    volumes:
      - mongodb:/data/db
  server:
    container_name: server
    stop_signal: SIGINT
    build: .
    image: "pablogolobar/order_server:${VERSION}"
    restart: always
    env_file:
      - app.env
    ports:
      - '${EXTERNAL_PORT}:${INTERNAL_PORT}'
    networks:
      - app
    depends_on:
      - mongodb

volumes:
  mongodb:
networks:
  app:
    driver: bridge
