version: '2.2'
services:
  django:
    build: .
    #command: sh -c "gunicorn --bind 0.0.0.0:8000 app.wsgi"
    volumes:
      - .:.
      - static_data:./static
    environment:
      - DEBUG=1
    ports:
      - 80:80
  db:
    image: postgres:12-alpine
    volumes:
      - pg_data:/var/lib/postegresql/data/
    #environment:
    #  - POSTGRES_DB=${POSTGRES_DB}
    #  - POSTGRES_USER=${POSTGRES_USER}
    #  - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #  - POSTGRES_HOST=${POSTGRES_HOST}
    #  - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "5432:5432"

  nginx:
    image: nginx:1.19.8-alpine
    depends_on:
      - django
    ports:
      - "80:80"
    volumes:
      - static_data:/var/www/html/static
      - ./nginx-conf.d:/etc/nginx/conf.d

volumes:
  static_data:
  pg_data: